[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "boto3>=1.41.2",
    "langchain-community>=0.4.1",
    "lxml>=6.0.2",
    "pip>=25.3",
    "python-dotenv>=1.2.1",
]
